name: new_workout_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.22.0
  flutter_riverpod: ^2.0.0
  cloud_firestore: ^4.13.0
  table_calendar: ^3.0.0
  pull_to_refresh: ^2.0.0
  fl_chart: ^0.70.2
  flutter_staggered_animations: ^1.1.1
  flutter_dotenv: ^5.2.1
  # Movement tracking dependencies
  pedometer: ^3.0.0
  flutter_activity_recognition: ^4.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  
