// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '***REMOVED***4c2e9e638fc275cea62a6c',
    messagingSenderId: '1020680571397',
    projectId: '***REMOVED***',
    authDomain: '***REMOVED***.firebaseapp.com',
    storageBucket: '***REMOVED***.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '***REMOVED***33ddc8448105f527a62a6c',
    messagingSenderId: '1020680571397',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '***REMOVED***d06374abbfa37beba62a6c',
    messagingSenderId: '1020680571397',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
    iosBundleId: 'com.example.workoutTrackerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '***REMOVED***d06374abbfa37beba62a6c',
    messagingSenderId: '1020680571397',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
    iosBundleId: 'com.example.workoutTrackerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '***REMOVED***3b82c309a315bb87a62a6c',
    messagingSenderId: '1020680571397',
    projectId: '***REMOVED***',
    authDomain: '***REMOVED***.firebaseapp.com',
    storageBucket: '***REMOVED***.appspot.com',
  );

}