// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgg2TE4PUSFrGCEgP318DlHHeCjwxAxP0',
    appId: '1:1020680571397:web:4c2e9e638fc275cea62a6c',
    messagingSenderId: '1020680571397',
    projectId: 'workout-tracker-a7b92',
    authDomain: 'workout-tracker-a7b92.firebaseapp.com',
    storageBucket: 'workout-tracker-a7b92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUUIaIXJsisgaVRdktbw-ontQzniZLe68',
    appId: '1:1020680571397:android:33ddc8448105f527a62a6c',
    messagingSenderId: '1020680571397',
    projectId: 'workout-tracker-a7b92',
    storageBucket: 'workout-tracker-a7b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsWAWUVZe4Pk3_XJ2N2emLszivBobKTjM',
    appId: '1:1020680571397:ios:d06374abbfa37beba62a6c',
    messagingSenderId: '1020680571397',
    projectId: 'workout-tracker-a7b92',
    storageBucket: 'workout-tracker-a7b92.appspot.com',
    iosBundleId: 'com.example.workoutTrackerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsWAWUVZe4Pk3_XJ2N2emLszivBobKTjM',
    appId: '1:1020680571397:ios:d06374abbfa37beba62a6c',
    messagingSenderId: '1020680571397',
    projectId: 'workout-tracker-a7b92',
    storageBucket: 'workout-tracker-a7b92.appspot.com',
    iosBundleId: 'com.example.workoutTrackerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgg2TE4PUSFrGCEgP318DlHHeCjwxAxP0',
    appId: '1:1020680571397:web:3b82c309a315bb87a62a6c',
    messagingSenderId: '1020680571397',
    projectId: 'workout-tracker-a7b92',
    authDomain: 'workout-tracker-a7b92.firebaseapp.com',
    storageBucket: 'workout-tracker-a7b92.appspot.com',
  );

}